name: 'Publish Meadow MPAK'
description: 'Publish Meadow MPAK to a Collection of Devices'
inputs:
  api_key:
    description: 'API Key'
    required: true
  collection_id:
    description: 'Device Collection ID'
    required: true
  host:
    description: 'API URL'
    required: false    
  metadata:
    description: 'Metadata for publish'
    required: false
runs:
  using: 'composite'
  steps:   
    - name: Publish Package
      run: |
        PACKAGE_ID="${{ env.PACKAGE_ID }}"
        if [[ -n "$PACKAGE_ID" ]]; then
          COMMAND="meadow cloud package publish $PACKAGE_ID --collectionId ${{ inputs.collection_id }} --apikey ${{ inputs.api_key }}"
          HOST_PARAM=""
          if [[ -n "${{ inputs.host }}" ]]; then
            HOST_PARAM="--host ${{ inputs.host }}"
          fi
          if [[ -n "${{ inputs.metadata }}" ]]; then
            COMMAND="$COMMAND --metadata '${{ inputs.metadata }}'"
          fi
          COMMAND="$COMMAND $HOST_PARAM"
          echo "Running command: $COMMAND"
          eval "$COMMAND"
        else
          echo "No PACKAGE_ID provided, unable to publish package."
        fi
      shell: bash
